### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by dannysmith** [jameshill/tfl#2]
I'm getting an error `Undefined method 'search' for Mechanize#File` from line 113 or `client.rb`...

```ruby
133      @current_card_id = @page.search('#CurrentCard').first.attributes['data-card-id'].value
```

The `form.submit` on line 108 is returning a Mechanize#File instead of a Mechanize#Page. Looks like it can be fixed by changing line 104 from `statement.forms[2]` to `statement.forms[3]`.

Having fixed that, I'm still running into errors - presumably because TfL have changed their markup. Before I dig too far into it I just wanted to know if this gem is still working for you?

Cheers 😄

**Comment by jameshill** [comment]
Hey @dannysmith,

I'm not running it anywhere at the moment, so I hadn't seen it pop up. But yes, I just checked it, and receive the same error. 

I was wondering when the day was going to come when the markup changed... I'd be nice to have a sanity check test that could run daily as part of the test suite, but to do that publicly we'd need a dummy card / account with known journey's on it.

**Comment by thomaswelton** [comment]
For the sanity tests I have an old bank card that has now expired that I have used for travel. 
I could give you the details for that card number. And for the TFL account, guess I could share the unique password I use for that with you in a private message so you can use it for the tests.
You can use travis to hide and encrypt sensitive information right? So the password and card details will remain private.
